### ISSUE TITLE
option to view transaction

### ISSUE THREAD

**Issue by justinvforvendetta** [peengo/vergeexplorer#1]
an option to display the full (raw) transaction would be really nice. this explorer is beautiful btw, excellent job!

**Comment by peengo** [comment]
> 
> 
> an option to display the full (raw) transaction would be really nice. this explorer is beautiful btw, excellent job!

Do you mean the JSON output of a transaction or a raw transaction as a hex string?

**Comment by peengo** [comment]
Do you mean the JSON output of a transaction or a raw transaction as a hex string?

**Comment by peengo** [comment]
added both :)

**Comment by justinvforvendetta** [comment]
saweeeeeeeeet
