### ISSUE TITLE
6.0.1

### ISSUE THREAD

**Issue by justinvforvendetta** [peengo/vergeexplorer#2]
dont mean to bother you, but can you please update to v6.0.1, and add a few v6 peers, maybe with addnode? or maybe delete the current peers.dat before restarting the 6.0.1 ? thanks!

**Comment by peengo** [comment]
can you please check the email I sent a couple of days ago to contact

**Comment by justinvforvendetta** [comment]
i dont have access to that one, but you can forward it to me also, justinvforvendetta@gmail.com

**Comment by justinvforvendetta** [comment]
also i love that you added the version daemon to the front. this explorer just keeps getting better and better!

**Comment by peengo** [comment]
updated daemon to v6.0.1
removed peers.dat

**Comment by peengo** [comment]
> 
> 
> i dont have access to that one, but you can forward it to me also, [email removed]

email sent

> 
> 
> i dont have access to that one, but you can forward it to me also, [email removed]

email sent :)

**Comment by peengo** [comment]
> 
> 
> i dont have access to that one, but you can forward it to me also, [email removed]

email sent :)
