### ISSUE TITLE
api ?

### ISSUE THREAD

**Issue by swat69** [peengo/vergeexplorer#4]
The api (and extended api) of the old explorer is used by some external services, for example Atomic Wallet
https://verge-blockchain.info/info

112.x.x.x - - [08/Mar/2020:12:18:42 +0100] "GET /ext/getaddress/DCt7UnxP7r8GrJRVgBNB9KbczWGuB2wH5V HTTP/1.1" 304 2307 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) atomic/2.14.0 Chrome/73.0.3683.121 Safari/537.36"
82.x.x.x - - [08/Mar/2020:12:18:42 +0100] "GET /ext/getaddress/DRm67P7pXfNuZXiec2jSbYNGqSh1XDBEth HTTP/1.1" 304 356 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) atomic/2.14.0 Chrome/73.0.3683.121 Safari/537.36"
93.x.x.x - - [08/Mar/2020:12:18:42 +0100] "GET /api/getrawtransaction?txid=4e938ac9b8d881fb7ab22fdd93eba2bf2138ad282e015c6543f3e74c7326d3f5&decrypt=1 HTTP/1.1" 200 2812 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) atomic/2.14.0 Chrome/73.0.3683.121 Safari/537.36"

**Do you have any plans to implement an api?**

**Comment by swat69** [comment]
Oh I just see Justin asked a similar question. -> enhancement

**Comment by peengo** [comment]
> 
> 
> Oh I just see Justin asked a similar question. -> enhancement

Where do you see his question? I can't find it.

**Comment by peengo** [comment]
There is an API but I don't have the documentation for it. Let me know what data you need and I'll provide you the endpoints

**Comment by swat69** [comment]
The question from Justin is a closed issue.


I compared the old and your new explorer.

It is possible to map/redirect all old URLs (/api and /ext) to the new URLs (e.g. /ext/getaddress/ -> /api/address) ?
Can you im implement the missing one?
We also need a page with a short documentation.
Or just create a clean API structure and pronounce a deadline with a hint to the new api,
hmm not sure about all this.
I just want to harm as less services as possible.


--------------------------------------------------------------	
	/api/getdifficulty		(old explorer)
	new: ?					(new: your new explorer)
--------------------------------------------------------------	
    /api/getconnectioncount
	new: not needed
--------------------------------------------------------------	
	/api/getblockcount
	new: ?
--------------------------------------------------------------	
    /api/getblockhash?index=3710000
	new: ?
--------------------------------------------------------------	
    /api/getblock?hash=eea348ac2353e3dd1fd2f20eb2bea225bf9933728f48f83a1f32a661db4c2336
	new: /api/block/eea348ac2353e3dd1fd2f20eb2bea225bf9933728f48f83a1f32a661db4c2336
--------------------------------------------------------------	
    /api/getrawtransaction?txid=4ac5d9c51642ab4d94a2a5d460b228d93e4aa6fcf73060f4c21dc881d041c75b&decrypt=0
    /api/getrawtransaction?txid=4ac5d9c51642ab4d94a2a5d460b228d93e4aa6fcf73060f4c21dc881d041c75b&decrypt=1
	new: /api/tx/4ac5d9c51642ab4d94a2a5d460b228d93e4aa6fcf73060f4c21dc881d041c75b

-------------------------------------
	Extended:
-------------------------------------
	/ext/getmoneysupply
	new: ?
--------------------------------------------------------------	
    /ext/getdistribution
	new: not needed
--------------------------------------------------------------	
    /ext/getaddress/DFxCJt8x6GMvFwuYNkDT9SZn7yHgkQbVxS
	new: /api/address/DFxCJt8x6GMvFwuYNkDT9SZn7yHgkQbVxS
--------------------------------------------------------------	
	/ext/getbalance/DFxCJt8x6GMvFwuYNkDT9SZn7yHgkQbVxS
	new: ?
--------------------------------------------------------------			
    getlasttxs (/ext/getlasttxs/count/min)
    Returns last [count] transactions greater than [min]
    Note: returned values are in satoshis
    /ext/getlasttxs/10/100
	new: not sure, if needed
		
----------------------------------	
	Linking (GET):
----------------------------------	

    /tx/4ac5d9c51642ab4d94a2a5d460b228d93e4aa6fcf73060f4c21dc881d041c75b
	new: OK
--------------------------------------------------------------	
    /block/1733320247b15ca2262be646397d1ffd6be953fa638ebb8f5dcbb4c2b91b34f1
	new: OK
--------------------------------------------------------------
    /address/DFxCJt8x6GMvFwuYNkDT9SZn7yHgkQbVxS
	new: OK
--------------------------------------------------------------	
    127.0.0.1:3001/qr/DFxCJt8x6GMvFwuYNkDT9SZn7yHgkQbVxS    (QR-Code)
	new: not needed

**Comment by peengo** [comment]
I'll add the missing endpoints this week.
For "/ext" and docs i'll see after I finish this first.

**Comment by peengo** [comment]
GET /api/difficulty
returns: data { difficulty: Number }

GET /api/blockcount
returns:  data { blockcount: Number }

GET /api/blockhash/:height
returns: data { blockhash: String }

GET /api/moneysupply
returns: data { moneysupply: Number }

GET /api/balance/:address
returns: data { balance: String }

How is this? :)

**Comment by swat69** [comment]
cool, excellent !
