### ISSUE TITLE
production: npm run build ?

### ISSUE THREAD

**Issue by swat69** [peengo/vergeexplorer#6]
I'm trying to run the production build:

>npm run build
>serve dist

But only the start page is visible with a red: There was an error.
Looks like the config to the backend server part is missing, don't know.
What is missing, how to run a production build?

-------------------------------------------------------------

npm run build
client@2.0.0 build /var/www/vergeexplorer/client
vue-cli-service build

error
VUE_APP_API_DEV_URL is missing.

â ¸  Building for production...Browserslist: caniuse-lite is outdated. Please run next command `npm update`
â ¼  Building for production...

 WARNING  Compiled with 3 warnings                                                                                                                                                                                               10:51:24 AM

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.3ca620a6.js (407 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (653 KiB)
      css/chunk-vendors.7a0cce53.css
      js/chunk-vendors.3ca620a6.js
      css/app.1fe3e937.css
      js/app.b091a6c3.js

 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                   Size              Gzipped

  dist/js/chunk-vendors.3ca620a6.js      406.70 KiB        124.75 KiB
  dist/js/app.b091a6c3.js                69.74 KiB         13.75 KiB
  dist/css/chunk-vendors.7a0cce53.css    176.09 KiB        23.19 KiB
  dist/css/app.1fe3e937.css              0.97 KiB          0.44 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
 
 
 
 serve dist
  Serving!                                                  
..                                                      
- Local:            http://localhost:5000        
- On Your Network:  http://195.201.128.169:5000 
-------------------------------------------------------------------
edit: the development version is running of course

**Comment by peengo** [comment]
In README I've only covered the steps on how to setup a development environment. The production environment is served differently. 

You need to redirect /api to localhost:5000

I am using this in nginx to do it
`location /api {
    rewrite ^/api(.*) $1 break;
    proxy_pass http://localhost:5000;
  }`

There will be a red error on the website if the backend is not running or reachable. 

Have you initialized the replicaset database with indexes and run the sync script and the backend API ?

"VUE_APP_API_DEV_URL is missing." this error is irrelevant if you are buidling for production, but for development it should be filled out. 

I'll try to dockerize this services for the future for easier setup.

**Comment by peengo** [comment]
I see you managed to set it up. Am I correct? :)

**Comment by swat69** [comment]
production build working now, access to the backend with Apache: 
ProxyPass /api/ http://127.0.0.1:5000/
