### ISSUE TITLE
Limit and offset params

### ISSUE THREAD

**Issue by dractw** [peengo/vergeexplorer#9]
https://github.com/peengo/vergeexplorer/blob/f78c89c1d83316e53e25e4e042cd90da48403dbf/server/routes/address.js#L34

Seem like it's more obvious use params like `https://verge-blockchain.info/api/address/txs/DSSW7bVfXnRRofW4KgRXaGGADtvpzogGG9?offset=0&limi=100` and don't put them in the url paths?

**Comment by peengo** [comment]
You are right. I'll refactor it :)

**Comment by peengo** [comment]
https://github.com/peengo/vergeexplorer/issues/11
